all:
	javac -g *.java && java TextMine

#v:
#	javac -g -verbose *.java && java ListOTen

#d:
#	javac -g *.java && java DoubleTrouble

#w:
#	gcc ex.c -Wall -g -o ex && ./ex

#v:
#	gcc ex.c -Wall -g -o ex && valgrind ./ex

#d:
#	gcc disassembler.c -Wall -g -o diss && ./diss


